# Generated by Django 5.0.4 on 2024-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book_dropped',
            field=models.ManyToManyField(null=True, related_name='Брошено', to='base.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='book_planning',
            field=models.ManyToManyField(null=True, related_name='Планнирую', to='base.book'),
        ),
        migrations.AddField(
            model_name='user',
            name='book_read',
            field=models.ManyToManyField(null=True, related_name='Прочитано', to='base.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='books_reading',
            field=models.ManyToManyField(null=True, related_name='Читаю', to='base.book'),
        ),
    ]
