# Generated by Django 5.0.4 on 2024-06-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_book_dropped_user_book_planning_user_book_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book_dropped',
            field=models.ManyToManyField(blank=True, related_name='Брошено', to='base.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_planning',
            field=models.ManyToManyField(blank=True, related_name='Планнирую', to='base.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_read',
            field=models.ManyToManyField(blank=True, related_name='Прочитано', to='base.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='books_reading',
            field=models.ManyToManyField(blank=True, related_name='Читаю', to='base.book'),
        ),
    ]
